### ISSUE TITLE
thread_1_7_2/project_1_t12/Run.java

### ISSUE THREAD

**Issue by rymuscle** [loveincode/Java-Multi-thread-Programming#2]
thread_1_7_2/project_1_t12/Run.java
书上说下面两句是用来判断thread对象所代表的线程是否停止
System.out.println("是否停止1？="+thread.interrupted());
System.out.println("是否停止2？="+thread.interrupted());

但是紧接着又说, thread.interrupted() 是测试”当前线程“main是否停止

那么到底判断的是main还是thread对象所代表的线程

**Comment by loveincode** [comment]
这里thread.interrupted()等同于 Thread.interrupted()
用来判断当前线程，当前线程就是main
